name: Loan_prediction
channels: 
  - defaults

dependencies:
  - python=3.10.13
  - pip<=23.2.1
  - pip:
    - mlflow==2.11.0
    - cloudpickle==3.0.0
    - lz4==4.3.2
    - numpy==1.26.1
    - packaging==23.1
    - psutil==5.9.0
    - pyyaml==6.0.1
    - scikit-learn==1.4.1.post1
    - scipy==1.12.0

